name: Format, lint, build and test

on:
    pull_request:
        branches:
            - senpai

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 14.17.0

            - name: Install dependencies
              run: yarn ci

            - name: Format
              run: yarn format

            - name: Lint
              run: yarn lint

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test
